name: Build Vue
on: 
  workflow_dispatch:
    branches: ["main"]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'ianpaul10'
        reponame: 'paul-family-cookbook'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        useyarn: true